name: release
on: 
  release:
    types: [published]

jobs:
  macOS:
    name: Build macOS
    runs-on: macOS-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🏗 swiftbuild
        run: |
          swift build -c release --arch arm64 --arch x86_64
      - name: 📦 Build archive
        run: |
          REPOSITORY_NAME=$(jq --raw-output '.repository.name' $GITHUB_EVENT_PATH)
          cd .build/apple/Products/Release/
          zip -r $REPOSITORY_NAME.zip $REPOSITORY_NAME
      - name: ⬆️ Upload to Release
        run: |
          REPOSITORY_NAME=$(jq --raw-output '.repository.name' $GITHUB_EVENT_PATH)
          ARTIFACT=.build/apple/Products/Release/$REPOSITORY_NAME.zip
          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
          CONTENT_LENGTH_HEADER="Content-Length: $(stat -f%z "$ARTIFACT")"
          CONTENT_TYPE_HEADER="Content-Type: application/zip"
          RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          FILENAME=$(basename $ARTIFACT)
          UPLOAD_URL="https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$FILENAME"
          echo "$UPLOAD_URL"
          curl -sSL -XPOST \
            -H "$AUTH_HEADER" -H "$CONTENT_LENGTH_HEADER" -H "$CONTENT_TYPE_HEADER" \
            --upload-file "$ARTIFACT" "$UPLOAD_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubuntuFocal:
    name: Build Linux ubuntuFocal
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup swiftenv
        run: |
          git clone https://github.com/kylef/swiftenv.git ~/.swiftenv
          export SWIFTENV_ROOT="$HOME/.swiftenv"
          export PATH="$SWIFTENV_ROOT/bin:$PATH"
          eval "$(swiftenv init -)"
          echo "$PATH" >> $GITHUB_PATH
      - run: rm -f .swift-version
      - name: Install Swift
        run: swiftenv install "5.7" --skip-existing
      - name: 🏗 swiftbuild
        run: |
          swift build -c release
      - name: 📦 Build archive
        run: |
          REPOSITORY_NAME=$(jq --raw-output '.repository.name' $GITHUB_EVENT_PATH)
          cd .build/release/
          zip -r $REPOSITORY_NAME-x86_64-dynamic_swift_5.7-ubuntu-focal.zip $REPOSITORY_NAME
      - name: ⬆️ Upload to Release
        run: |
          REPOSITORY_NAME=$(jq --raw-output '.repository.name' $GITHUB_EVENT_PATH)
          ARTIFACT=.build/release/$REPOSITORY_NAME-x86_64-dynamic_swift_5.7-ubuntu-focal.zip
          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
          CONTENT_LENGTH_HEADER="Content-Length: $(stat --format=%s "$ARTIFACT")"
          CONTENT_TYPE_HEADER="Content-Type: application/zip"
          RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          FILENAME=$(basename $ARTIFACT)
          UPLOAD_URL="https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$FILENAME"
          echo "$UPLOAD_URL"
          curl -sSL -XPOST \
            -H "$AUTH_HEADER" -H "$CONTENT_LENGTH_HEADER" -H "$CONTENT_TYPE_HEADER" \
            --upload-file "$ARTIFACT" "$UPLOAD_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 🏗 swiftbuild static
        run: |
           swift build -c release -Xswiftc -static-executable
      - name: 📦 Build archive  
        run: |
          REPOSITORY_NAME=$(jq --raw-output '.repository.name' $GITHUB_EVENT_PATH)
          cd .build/release/
          zip -r $REPOSITORY_NAME-x86_64-static-ubuntu-focal.zip $REPOSITORY_NAME
      - name: ⬆️ Upload to Release
        run: |
          REPOSITORY_NAME=$(jq --raw-output '.repository.name' $GITHUB_EVENT_PATH)
          ARTIFACT=.build/release/$REPOSITORY_NAME-x86_64-static-ubuntu-focal.zip
          AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
          CONTENT_LENGTH_HEADER="Content-Length: $(stat --format=%s "$ARTIFACT")"
          CONTENT_TYPE_HEADER="Content-Type: application/zip"
          RELEASE_ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          FILENAME=$(basename $ARTIFACT)
          UPLOAD_URL="https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$RELEASE_ID/assets?name=$FILENAME"
          echo "$UPLOAD_URL"
          curl -sSL -XPOST \
            -H "$AUTH_HEADER" -H "$CONTENT_LENGTH_HEADER" -H "$CONTENT_TYPE_HEADER" \
            --upload-file "$ARTIFACT" "$UPLOAD_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}